image: openjdk:11

stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
test:
  stage: test
  script:
    ./gradlew test
  artifacts:
    paths:
      - build/test-results/test/TEST*.xml
deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=simple-autos-jesse-kiwi --api-key=$HEROKU_API_KEY
  only:
    - master